import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import TranslationsProvider from "./_providers/translation/TranslationsProvider";
import initTranslations from "./i18n";
import i18nNamespaces from "@/i18nNamespaces";
import detectDeviceLocale from "@/lib/detectDeviceLocale";
import { ApolloProvider } from "./_providers/apollo/ApolloProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const acceptLanguage = headersList.get("accept-language");
  const locale = detectDeviceLocale(acceptLanguage);

  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloProvider>
          <TranslationsProvider
            locale={locale}
            namespaces={i18nNamespaces}
            resources={resources}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem={true}
            >
              {children}
            </ThemeProvider>
          </TranslationsProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
